name: CI Pipeline - Faleproxy

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  run-tests:
    name: Run Tests on Node.js
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install project dependencies
        run: npm ci

      - name: Execute test suite
        run: npm run test:ci

      - name: Save coverage output
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.node }}
          path: coverage/

  deploy-to-vercel:
    name: Deploy to Vercel (Production)
    needs: run-tests
    if: ${{ success() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Prepare Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Sync Vercel environment
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build production assets
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to production
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
